### ISSUE TITLE
Consistantly getting a python code error.

### ISSUE THREAD

**Issue by Hime0698** [DragoonAethis/itch-dl#14]
![CleanShot 2024-04-16 at 11 48 57@2x](https://github.com/DragoonAethis/itch-dl/assets/26724000/b385ac31-86c0-46fb-aa40-14df95a7764b)
I am consistently getting this error on various different games when I try to download my whole library. 

Is there any fix to this, or a way to bypass the error and download everything but the erroring ones?

**Comment by TheFrenchGhosty** [comment]
@Hime0698 Just run the script on a loop, it starts from a different "position" everytime so if you run it often enough, everything but the impossible-to-download files will be downloaded

**Comment by DragoonAethis** [comment]
Okay, looks like this is an issue with all access restricted pages. I've fixed the crash in 0.4.1, but restricted titles can't be downloaded for now. The rest of the library/bundle should go through normally. See #16 for a tracker on that. Thanks for your report!

**Comment by TheFrenchGhosty** [comment]
@DragoonAethis works exactly how it should, thanks
