### ISSUE TITLE
The game won't download

### ISSUE THREAD

**Issue by Werkest** [DragoonAethis/itch-dl#18]
It says that the download is complete, but the folder where the game should be is empty

```
INFO:root:Found 1 URL(s).
INFO:root:Fetching all download keys...
INFO:root:Downloading page 1 (found 0 keys total)
INFO:root:Fetched 0 download keys.
Games:   0%|                                                                                   | 0/1 [00:00<?, ?game/s]INFO:root:Downloading https://fizzd.itch.io/a-dance-of-fire-and-ice
https://img.itch.zone/aW1nLzE4MDIwODUucG5n/original/M7FLNm.png:  20%|██▊           | 73.6k/366k [00:00<00:00, 9.29MB/s]
INFO:root:Finished job https://fizzd.itch.io/a-dance-of-fire-and-ice (A Dance of Fire and Ice)0/374623 [00:00<?, ?it/s]
Games: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.89s/game]
Download complete!
```

**Comment by DragoonAethis** [comment]
This is a paid game and itch-dl could not fetch any download keys for your account - are you sure you have it purchased and have it attached to your account?

If you purchased it in a bundle, itch by default does not attach download keys for each title to your account to prevent flooding your library with hundreds of games. If you see something like this, you need to click Download here once:

![image](https://github.com/DragoonAethis/itch-dl/assets/1546665/fd6e1587-7235-452b-be20-3ff6170dc155)
