### ISSUE TITLE
how to install a paid version, the dl only detects the demo

### ISSUE THREAD

**Issue by SussyBaka553** [DragoonAethis/itch-dl#19]
how to install a game with a demo but with a paid version?

sorry I'm new to coding, the itch-dl only detects the demo and also I'm not sure where is the downloaded game will appear?

**Comment by DragoonAethis** [comment]
You must purchase the game to download the full version. On itch.io, once the full game is in [your library](https://itch.io/my-purchases), running `itch-dl <url>` will download it in the directory you have run this command in.

If you have purchased the game, it is in your library and it still only picks up the demo, send the link here and I will check why the downloader does not pick up the full version links.
