### ISSUE TITLE
file size is different than expected. download failed

### ISSUE THREAD

**Issue by estatistics** [DragoonAethis/itch-dl#21]
itch-dl --mirror-web --api-key ............................................  https://anttihaavikko.itch.io/coup-ahoo
INFO:root:Found 1 URL(s).
INFO:root:Fetching all download keys...
INFO:root:Downloading page 1 (found 0 keys total)
INFO:root:Fetched 3 download keys.
Games:   0%|                                                                                                                                                                              | 0/1 [00:00<?, ?game/s]INFO:root:Downloading https://anttihaavikko.itch.io/coup-ahoo
/uploads/11449738/download: 100%| 54.5k/54.5k [00:00<00:00, 404kB/s]
https://img.itch.zone/aW1hZ2UvMjk2NTM2MS8xNzczNjAzOS5qcGc=/original/R2BnaA.jpg: 100%|138k/138k [00:00<00:00, 523kB/s]
https://img.itch.zone/aW1hZ2UvMjk2NTM2MS8xNzczNjA1MC5qcGc=/original/nUiKYa.jpg:  71%|                    | 110k/154k [00:00<00:00, 5.66MB/s]
https://img.itch.zone/aW1hZ2UvMjk2NTM2MS8xNzczNjAzOC5qcGc=/original/rSYS19.jpg: 100%|151k/151k [00:00<00:00, 3.08MB/s]
https://img.itch.zone/aW1hZ2UvMjk2NTM2MS8xNzczNjA0MC5qcGc=/original/0UQy5T.jpg: 100%| 170k/170k [00:00<00:00, 1.51MB/s]
https://img.itch.zone/aW1hZ2UvMjk2NTM2MS8xNzczNjA0MS5qcGc=/original/N0Mel8.jpg: 100%| 139k/139k [00:00<00:00, 2.84MB/s]
https://img.itch.zone/aW1nLzE3NzM2MDg2LmdpZg==/original/haGnaJ.gif:  93%|   | 2.27M/2.44M [00:00<00:00, 6.09MB/s]
ERROR:root:Game Coup Ahoo has download errors: ["File size is 55859, expected 193962 for upload {'build_id': 1117012, 'id': 11449738, 'channel_name': 'html5', 'type': 'html', 'size': 193962, 'filename': 'coup-ahoo-html5.zip', 'position': 0, 'created_at': '2024-09-11T15:40:06.000000000Z', 'storage': 'build', 'build': {'id': 1117012, 'created_at': '2024-11-07T07:17:36.000000000Z', 'version': 10, 'parent_build_id': 1116713, 'updated_at': '2024-11-07T07:17:46.000000000Z', 'upload_id': 11449738}, 'game_id': 2965361, 'updated_at': '2024-11-07T07:17:46.000000000Z', 'traits': {}}"]
INFO:root:Finished job https://anttihaavikko.itch.io/coup-ahoo (Coup Ahoo)
Games: 100%|1/1 [00:09<00:00,  9.47s/game]
Download complete!

Download failed for https://anttihaavikko.itch.io/coup-ahoo:
- File size is 55859, expected 193962 for upload {'build_id': 1117012, 'id': 11449738, 'channel_name': 'html5', 'type': 'html', 'size': 193962, 'filename': 'coup-ahoo-html5.zip', 'position': 0, 'created_at': '2024-09-11T15:40:06.000000000Z', 'storage': 'build', 'build': {'id': 1117012, 'created_at': '2024-11-07T07:17:36.000000000Z', 'version': 10, 'parent_build_id': 1116713, 'updated_at': '2024-11-07T07:17:46.000000000Z', 'upload_id': 11449738}, 'game_id': 2965361, 'updated_at': '2024-11-07T07:17:46.000000000Z', 'traits': {}}
- ---------------------------------------------------------------------------------------
 sudo pip3 install --break-system-packages itch-dl

Collecting itch-dl
  Using cached itch_dl-0.4.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.3 in /usr/lib/python3/dist-packages (from itch-dl) (4.12.3)
Requirement already satisfied: lxml<6.0.0,>=5.2.1 in /usr/lib/python3/dist-packages (from itch-dl) (5.3.0)
Collecting pydantic<2.0.0,>=1.10.15 (from itch-dl)
  Downloading pydantic-1.10.19-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (152 kB)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in /usr/lib/python3/dist-packages (from itch-dl) (2.32.3)
Collecting tqdm<5.0.0,>=4.66.2 (from itch-dl)
  Downloading tqdm-4.67.0-py3-none-any.whl.metadata (57 kB)
Collecting urllib3<2.0.0,>=1.26.18 (from itch-dl)                                                                                                                                                                 
  Using cached urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)                                                                                                                                              
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4<5.0.0,>=4.12.3->itch-dl) (2.6)                                                                                
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/lib/python3/dist-packages (from pydantic<2.0.0,>=1.10.15->itch-dl) (4.12.2)                                                                       
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.31.0->itch-dl) (2024.8.30)                                                                           
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.31.0->itch-dl) (3.3.2)                                                                         
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3.0.0,>=2.31.0->itch-dl) (3.8)                                                                                       
Using cached itch_dl-0.4.1-py3-none-any.whl (17 kB)                                                                                                                                                               
Downloading pydantic-1.10.19-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)                                                                                                                  
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 4.4 MB/s eta 0:00:00
Downloading tqdm-4.67.0-py3-none-any.whl (78 kB)                                                                                                                                                                  
Using cached urllib3-1.26.20-py2.py3-none-any.whl (144 kB)                                                                                                                                                        
Installing collected packages: urllib3, tqdm, pydantic, itch-dl                                                                                                                                                   
  Attempting uninstall: urllib3                                                                                                                                                                                   
    Found existing installation: urllib3 2.0.7
error: uninstall-no-record-file

× Cannot uninstall urllib3 2.0.7
╰─> The package's contents are unknown: no RECORD file was found for urllib3.

hint: The package was installed by debian. You should check if it can uninstall the package.

**Comment by DragoonAethis** [comment]
It looks like the API returns the file size of the single, uncompressed file within the archive (index.html in it is exactly 194830), while the archive itself is a little smaller. I added a change that tries to detect the archive content size for Zip and Tar archives - your game now downloads correctly without errors, please retry your download with itch-dl 0.4.3 (just published on PyPI). Thanks for the bug report!
