### ISSUE TITLE
NotImplementedError: Unknown infobox block name 'Code license'

### ISSUE THREAD

**Issue by avivace** [DragoonAethis/itch-dl#6]
Is there a quick way to skip this error?

**Comment by DragoonAethis** [comment]
Done, check out https://pypi.org/project/itch-dl/ 0.3.2 - I'll try to dump all GBA Jam games to see if anything else needs fixups, too

**Comment by avivace** [comment]
> Done, check out [pypi.org/project/itch-dl](https://pypi.org/project/itch-dl/) 0.3.2 - I'll try to dump all GBA Jam games to see if anything else needs fixups, too

Amazing, thanks @DragoonAethis ! Dumping `gbajam22` completes now ;)
